version: '3'
services:
  # mqtt server
  mqtt-sandbox:
    image: "eclipse-mosquitto"
    ports: 
      - 1884:1883
      - 9001:9001
  # influxdb
  influxdb:
    build:
      context: ./images/influxdb/
      dockerfile: ./Dockerfile
    image: "influxdb"
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/config/:/etc/influxdb/
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089/udp"
  # telegraf
  telegraf:
    build:
      context: ./images/telegraf/
      dockerfile: ./Dockerfile
    image: "telegraf"
    links:
      - influxdb
    volumes:
      - ./telegraf/:/etc/telegraf/
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
  # kapacitor
  kapacitor:
      build:
        context: ./images/kapacitor/
        dockerfile: ./Dockerfile
      image: "kapacitor"
      volumes:
        - ./kapacitor/data/:/var/lib/kapacitor
        - ./kapacitor/config/:/etc/kapacitor/
      links:
        - influxdb
      ports:
        - "9092:9092"
  # chronograf
  chronograf:
    build:
      context: ./images/chronograf
      dockerfile: ./Dockerfile
    image: "chrono_config"
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
    volumes:
      - ./chronograf/data/:/var/lib/chronograf/
    links:
      - influxdb
      - kapacitor
    ports:
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb
      - telegraf
